package com.example.mysticmindfx;

public enum Message {
    SIGN_IN_LINK,
    SIGN_UP_LINK,
    FILL_ALL_FIELDS,
    EMAIL_EXISTS,
    PASSWORD_REQS,
    EMAILS_DO_NOT_MATCH,
    PASSWORDS_DO_NOT_MATCH,
    SIGN_UP_SUCCESS_TITLE,
    SIGN_UP_SUCCESS_HEADER,
    SIGN_UP_SUCCESS_CONTENT,
    EMAIL_NOT_FOUND,
    INCORRECT_PASSWORD,
    LOGIN_SUCCESS_TITLE,
    LOGIN_SUCCESS_HEADER,
    LOGIN_SUCCESS_CONTENT,
    DELETE_CHAT_CONFIRMATION,
    RENAME_CHAT,
    REMOVE_CHAT,
    REMOVE_CHAT_TITLE

}
